---
- name: Update packages on Ubuntu
  hosts: your_ubuntu_servers
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes

- name: Update packages on Fedora/Red Hat
  hosts: your_fedora_servers
  become: yes
  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes

    - name: Upgrade packages
      dnf:
        upgrade: yes
        autoremove: yes